# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e6f9ed19-e77d-4a80-816c-d5339b787c5d'
  imageRepository: 'vardanssamplespring'
  containerRegistry: 'testing99.azurecr.io'
  dockerfilePath: 'docker-spring-boot/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'testing994675-auth'

  vmImageName: 'ubuntu-latest'
#pool: new-agentpool

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    # vmImageName: 'ubuntu-latest'
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            sleep 3000
  - job: test
    displayName: test
    pool:
      name: new-agentpool
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            sleep 3000
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: new-agentpool
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            sleep 3000
    

